name: Central Validation

on:
  push:
    branches-ignore:
      - main
      - develop

jobs:
  verificar_version:
    name: Control de Versiones
    uses: fvalenzuela-dev/.github/.github/workflows/version-check-new.yml@main
    with:
      version_file: 'package.json'
      base_branch: 'main'
    secrets:
      GITHUB_TOKEN_CUSTOM: ${{ secrets.GITHUB_TOKEN }}
  build_and_test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run tests with coverage
        run: npm run test:coverage

      - name: Build application
        run: npm run build

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/lcov.info
          retention-days: 1
  codacy_coverage:
    name: Codacy Coverage
    needs: [build_and_test]
    uses: fvalenzuela-dev/.github/.github/workflows/codacy-coverage.yml@d4f30734ca2858a553e062468515b7eb348c2365
    with:
      coverage_report_path: 'coverage/lcov.info'
    secrets:
      CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
